### ISSUE TITLE
Wrong url parameters generation for controller actions returning statuses

### ISSUE THREAD

**Issue by suvroc** [ploeh/Hyprlinkr#39] opened 2015-10-16 14:29 UTC
When we use action definition with `HttpRequestMessage` parameter

    public HttpResponseMessage Get(HttpRequestMessage request, int id)
    {
    }

`this.Url.GetLink<StatusValuesController>(a => a.Get(request, key));` produce url like this

    /apiv1/Values/3?request=Method%3A%20POST%2C%20RequestUri...

`request` parameter is not a part of routing and it souldn't be in generated url.

It only works fine if I pass null for `request` parameter

    this.Url.GetLink<StatusValuesController>(a => a.Get(null, key));

**Comment by ploeh** [comment] 2015-10-17 13:01
Thank you for writing. AFAICT, this is essentially a duplicate of #16, so I'm going to close this issue.

You may also find useful information in #28.

Feel free to continue the discussion either here, or in one of the other issues, if you feel your question hasn't been answered. We can also reopen this issue if I misinterpreted it.

**Closed by ploeh** 2015-10-17 13:01 UTC
